---
- name: "Build container with ansible"
  hosts: website
  
  become: true
  vars:
    ansible_become_password: ""
    ansible_user: 'ubuntu'
  tasks:

   - name: change current dir to project
     command: ls 

   - name: print path
     command: pwd
     register: pwd_output

   - name: Display registered output
     debug:
        var: pwd_output.stdout

   # - name: Clone GitHub repository
   #   git:
   #      repo: https://github.com/Abdelrhman1Ragab2/simple-project-ci-cd.git
   #      dest: /home/ubuntu/project
        
   - name: print content of  dockerfile
     command: cat /home/ubuntu/project/Dockerfile
     register: cat_output

   - name: Display registered output
     debug:
        var: cat_output.stdout
        
   - name: build docker image from dockerfile
     command: docker build -t rayban-image .

   - name: run container from image
     command: docker run -d --name rayban -p 80:80 rayban-image
      
      
 



# - name: "Build container with ansible"
#   hosts: localhost
#   tasks:
#     - name: stop running container
#       command: docker stop rayban
#       ignore_errors: yes

#     - name: remove stopped container
#       command: docker rm rayban
#       ignore_errors: yes

#     - name: remove used image
#       command: docker rmi rayban-image
#       ignore_errors: yes

#     - name: build docker image from dockerfile
#       command: docker build -t rayban-image .

#     - name: create tag to image
#       command: docker tag rayban-image <dockerhub user/repository name>

#     - name: push image to dockerhub
#       command: docker push <dockerhub user/repository name>

#     - name: run container from image
#       command: docker run -d --name rayban -p 80:80 rayban-image
